remote_theme: jonaharagon/jekyll-bootstrap-theme
title: Chris Goerner
description: Senior DevOps Engineer

author:
  name: 'Chris Goerner'
  email: 'chris@goerner.com.au'

plugins:
  - jekyll-feed
  - jekyll-seo-tag